name: Terraform Module Releases
on:
  push:
    branches:
      - master
    paths:
      - "**/*.tpl"
      - "**/*.py"
      - "**/*.tf"
      - ".github/workflows/release.yml"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.x
      - name: Install Semantic Release and plugins
        run: |
          npm install semantic-release @semantic-release/exec @semantic-release/changelog @semantic-release/github
      - name: Create Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
